---
title: "AlphaDiversity"
author: "Riko"
date: "2026-04-25"
output: html_document
---
```{r}
library(tidyverse)
library(phyloseq)
library(readxl)
library(vegan)
library(ggpubr)
library(microbiome)
library(indicspecies)
library(writexl)
library(ANCOMBC)
library(ggpubr)



metadata = read_excel('parkinsons_md copy.xlsx')
taxonomy = read.delim('taxonomy-copy.tsv', row.names = 1)
tree = read_tree('tree.nwk-copy')
counts = read.delim('feature-table-copy.txt', skip=1, row.names=1) # First line is not data


taxonomy_formatted = taxonomy %>%
  separate(col= Taxon,
           into = c('Domain', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'),
           sep = '; ', fill = 'right') %>%
  select(-Confidence) %>%
  as.matrix()

counts_formatted = as.matrix(counts)
metadata <- metadata %>% 
  column_to_rownames("#SampleID")

ps = phyloseq(sample_data(metadata),
              otu_table(counts_formatted, taxa_are_rows = TRUE),
              tax_table(taxonomy_formatted),
              tree)

ps_subset = subset_samples(ps, Disease == "PD")

metadata_PD = data.frame(ps_subset@sam_data)

PD_sum = metadata_PD |>
  group_by(Sex) |>
  summarise(
    p33_alpha_carotene = quantile(Alpha_carotene, 0.33, na.rm = TRUE),
    p67_alpha_carotene = quantile(Alpha_carotene, 0.67, na.rm = TRUE),
    p33_beta_carotene = quantile(Beta_carotene, 0.33, na.rm = TRUE),
    p67_beta_carotene = quantile(Beta_carotene, 0.67, na.rm = TRUE),
    p33_Copper = quantile(Copper, 0.33, na.rm = TRUE),
    p67_Copper = quantile(Copper, 0.67, na.rm = TRUE),
    p33_selenium = quantile(Selenium, 0.33, na.rm = TRUE),
    p67_selenium = quantile(Selenium, 0.67, na.rm = TRUE),
    p33_Vitamin_A = quantile(Vitamin_A, 0.33, na.rm = TRUE),
    p67_Vitamin_A = quantile(Vitamin_A, 0.67, na.rm = TRUE),
    p33_Vitamin_C = quantile(Vitamin_C, 0.33, na.rm = TRUE),
    p67_Vitamin_C = quantile(Vitamin_C, 0.67, na.rm = TRUE),
    p33_Vitamin_E = quantile(Vitamin_E, 0.33, na.rm = TRUE),
    p67_Vitamin_E = quantile(Vitamin_E, 0.67, na.rm = TRUE),
    p33_Car_total = quantile(Carotene_total, 0.33, na.rm = TRUE),
    p67_Car_total = quantile(Carotene_total, 0.67, na.rm = TRUE))
PD_sum


PD_grouped = metadata_PD %>%
  mutate(Age_onset =
      case_when(Age_onset  < 50 ~ "40s",
                between(Age_onset, 50, 59) ~ "50s",
                between(Age_onset, 60, 69) ~ "60s",
                Age_onset >= 70 ~ "70s")) 



PD_male_grouped <- subset(PD_grouped, Sex == "Male") #122 patients
PD_female_grouped <- subset(PD_grouped, Sex == "Female") #75 patients 
PD_male_grouped
PD_female_grouped



PD_binned = PD_grouped |>
  mutate(Alpha_carotene =
           case_when(Sex == "Male" & Alpha_carotene > 548.2559 ~ "High",
                     Sex == "Male" & Alpha_carotene < 189.350 ~ "Low",
                     Sex == "Male" & Alpha_carotene ~ "Typical",
                     Sex == "Female" & Alpha_carotene > 575.7513 ~ "High",
                     Sex == "Female" & Alpha_carotene < 541.904 ~ "Low",
                     Sex == "Female" & Alpha_carotene ~ "Typical"),
         Beta_carotene = 
           case_when(Sex == "Male" & Beta_carotene > 3542.550 ~ "High",
                     Sex == "Male" & Beta_carotene < 2229.975 ~ "Low",
                     Sex == "Male" & Beta_carotene ~ "Typical",
                     Sex == "Female" & Beta_carotene > 5100.328 ~ "High",
                     Sex == "Female" & Beta_carotene < 3178.988 ~ "Low",
                     Sex == "Female" & Beta_carotene ~ "Typical"),
         Copper = 
           case_when(Sex == "Male" & Copper > 1.200000 ~ "High",
                     Sex == "Male" & Copper < 0.8431575 ~ "Low",
                     Sex == "Male" & Copper ~ "Typical",
                     Sex == "Female" & Copper > 1.285575 ~ "High",
                     Sex == "Female" & Copper < 1.0000000 ~ "Low",
                     Sex == "Female" & Copper ~ "Typical"),
         Selenium = 
           case_when(Sex == "Male" & Selenium > 58.39314 ~ "High",
                     Sex == "Male" & Selenium < 42.72238 ~ "Low",
                     Sex == "Male" & Selenium ~ "Typical",
                     Sex == "Female" & Selenium > 65.45464 ~ "High",
                     Sex == "Female" & Selenium < 44.83593 ~ "Low",
                     Sex == "Female" & Selenium ~ "Typical"),
         Vitamin_A =
           case_when(Sex == "Male" & Vitamin_A > 328.4200 ~ "High",
                     Sex == "Male" & Vitamin_A < 191.623 ~ "Low",
                     Sex == "Male" & Vitamin_A ~ "Typical",
                     Sex == "Female" & Vitamin_A > 419.0756 ~ "High",
                     Sex == "Female" & Vitamin_A < 223.012 ~ "Low",
                     Sex == "Female" & Vitamin_A ~ "Typical"),
         Vitamin_C =
           case_when(Sex == "Male" & Vitamin_C > 119.2655 ~ "High",
                     Sex == "Male" & Vitamin_C < 82.31294 ~ "Low",
                     Sex == "Male" & Vitamin_C ~ "Typical",
                     Sex == "Female" & Vitamin_C > 165.2305 ~ "High",
                     Sex == "Female" & Vitamin_C < 108.04810 ~ "Low",
                     Sex == "Female" & Vitamin_C ~ "Typical"),
         Vitamin_E =
           case_when(Sex == "Male" & Vitamin_E > 12.09911 ~ "High",
                     Sex == "Male" & Vitamin_E < 8.652149 ~ "Low",
                     Sex == "Male" & Vitamin_E ~ "Typical",
                     Sex == "Female" & Vitamin_E > 14.34675 ~ "High",
                     Sex == "Female" & Vitamin_E < 10.580000 ~ "Low",
                     Sex == "Female" & Vitamin_E ~ "Typical"),
         Carotene_total =
           case_when(Sex == "Male" & Carotene_total > 4064.849 ~ "High",
                     Sex == "Male" & Carotene_total < 2495.81 ~ "Low",
                     Sex == "Male" & Carotene_total ~ "Typical",
                     Sex == "Female" & Carotene_total > 5691.588 ~ "High",
                     Sex == "Female" & Carotene_total < 3636.83 ~ "Low",
                     Sex == "Female" & Carotene_total ~ "Typical"))
PD_binned
ps_jeremy_data = ps_subset
sample_data(ps_jeremy_data) = sample_data(PD_binned)

```


#Vitamin C for manuscript: (With jitter)
```{r}
psrare = ps_jeremy_data %>% rarefy_even_depth(sample.size = 9555, rngseed = 421)

table(sample_sums(psrare))

set.seed(421)
p1 = plot_richness(psrare, x = 'Vitamin_C', 
                  measures = c('Shannon'),
                  color = 'Vitamin_C',
                  )
p1

p1data = p1$data
p1data

vars <- c("Alpha_carotene","Beta_carotene","Copper","Selenium",
          "Vitamin_A","Vitamin_C","Vitamin_E","Carotene_total")
p1data <- p1$data %>%
  dplyr::filter(!is.na(value)) %>% 
  tidyr::drop_na(dplyr::all_of(vars))

p1data

p1data$Vitamin_C = factor(p1data$Vitamin_C, levels = c("Low", "Typical", "High"))


alpha_plot_manu <- ggplot(p1data, aes(x = Vitamin_C,
                                        y = value)) +
  stat_boxplot(geom = "errorbar", width = 0.2) +
  geom_boxplot(aes(fill=Vitamin_C), outlier.shape = NA) +
  geom_jitter(height = 0, width = 0.2, size = 0.8, alpha = 0.6)+
  scale_fill_manual(values = c("High" = "#F5793A", "Low" = "#E03C8A", "Typical" = "#005AB5")) +
  labs(x = "Vitamin C intake levels", y = "Shannon Diversity Measure") +
  ylim(1, 7)  +
  theme_classic(base_size = 22) +
  theme(legend.position = "none")
alpha_plot_manu

comparison = list( c('Low', 'Typical'),
                   c('Low', 'High'),
                   c('Typical', 'High'))

alpha_plot_final_manu = alpha_plot_manu + 
  stat_compare_means(comparisons = comparison, method = 'wilcox.test', size = 7)+
  scale_y_continuous(expand = expansion(mult = c(0.06, 0.09)))
alpha_plot_final_manu

ggsave('Alpha Diversity Vitamin C_manuscript.jpeg',
       plot = alpha_plot_final_manu,
       height= 5, width = 7)


```

# All nutrients except vitC for manuscript supplemental:
```{r}
library(stringr)
library(ggplot2)
library(ggh4x)

psrare <- ps_jeremy_data %>% 
  rarefy_even_depth(sample.size = 9555, rngseed = 421)

set.seed(421)
p <- plot_richness(psrare,
                   x = 'Alpha_carotene',  # just needed to generate the dataframe
                   measures = c('Shannon'),
                   color = 'Alpha_carotene')

vars <- c("Alpha_carotene","Beta_carotene","Copper","Selenium",
          "Vitamin_A","Vitamin_E","Carotene_total")

pdata_long <- p$data %>%
  dplyr::filter(!is.na(value)) %>% 
  tidyr::pivot_longer(cols = dplyr::all_of(vars),
                      names_to = "nutrient",
                      values_to = "intake_level") %>%
  dplyr::filter(!is.na(intake_level))

pdata_long <- pdata_long %>%
  mutate(nutrient = str_to_title(gsub("_", " ", nutrient)))

pdata_long <- pdata_long %>%
  mutate(intake_level = factor(intake_level, levels = c("Low", "Typical", "High")))




panel_labels <- pdata_long %>%
  dplyr::distinct(nutrient) %>%
  dplyr::arrange(nutrient) %>%   # respects facet order
  dplyr::mutate(label = LETTERS[seq_len(n())])


comparisons = list(c('Low', 'Typical'),
                  c('Low', 'High'),
                  c('Typical', 'High'))


p_formatted <- pdata_long %>%
  ggplot(aes(x = intake_level, y = value, fill = intake_level)) +
  stat_boxplot(geom = "errorbar", width = 0.2) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, height = 0, size = 0.8, alpha = 0.6) +
  scale_fill_manual(values = c("High" = "#F5793A", "Low" = "#E03C8A", "Typical" = "#005AB5")) +
  facet_wrap(~nutrient, scales = "free_x", ncol = 3) +
   geom_text(
    data = panel_labels,
    aes(x = -Inf, y = Inf, label = label),
    inherit.aes = FALSE,
    hjust = -0.6,
    vjust = 1.6,
    size = 8,
    fontface = "bold"
  ) +
theme_classic(base_size = 22) +
  theme(strip.text = element_text(face = "bold", size = 15),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") +
  labs(x = 'Antioxidant Intake Levels', y = 'Shannon Diversity', fill = 'Nutrient Intake \nLevel') +
  stat_compare_means(comparisons = comparisons, method = 'wilcox.test', 
                     label.y.npc = 0.95, step.increase = 0.1, size = 5) +
  scale_y_continuous(expand = expansion(mult = c(0.02, 0.12)))

p_formatted

ggsave('Alpha_Diversity_supp.jpeg',
       plot = p_formatted,
       height = 13, width = 14,  dpi = 1500)
```