---
title: "differential_abundance_v2"
output: html_document
date: "2026-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Library
```{r}
library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)
library(microbiome)
library(indicspecies)
library(writexl)
library(ANCOMBC)
library(ggpubr)
library(patchwork)
library(ggsignif)
library(rempsyc)
```
##Loading Phyloseq Object
```{r}
ps_vc = readRDS('phyloseq.rds')
set.seed(421)
ps_genus_vc = tax_glom(ps_vc, 'Genus')


metadata <- data.frame(sample_data(ps_genus_vc))
metadata$Vitamin_C <- factor(metadata$Vitamin_C)
metadata$Vitamin_C <- relevel(metadata$Vitamin_C, ref = "Low")
sample_data(ps_genus_vc) <- metadata
```

## ANCOM-BC2
```{r}

output_genus_vc = ancombc2( ps_genus_vc,
          fix_formula = "Vitamin_C",
          p_adj_method = "BH",
          prv_cut = 0.1, 
          pseudo_sens = FALSE)

# Filtering out Chloroplast sequences
sig_taxa_asv = output_genus_vc$res %>% 
  filter(q_Vitamin_CHigh < 0.05) %>% 
  filter(taxon != "dd228d51656bfa4af8a21464f726fbfc") %>% 
  select(taxon) %>% 
  pull()

tax_df = as.data.frame(tax_table(ps_vc)) %>% 
  rownames_to_column(var = 'taxon') %>% 
  filter(taxon %in% sig_taxa_asv) 

vc_daa_sig = output_genus_vc$res %>% 
  filter(q_Vitamin_CHigh < 0.05) %>% 
  full_join(tax_df, by = 'taxon') %>% 
  select(taxon, lfc_Vitamin_CHigh, q_Vitamin_CHigh, Genus) %>% 
  arrange(lfc_Vitamin_CHigh)%>% 
  mutate(q_label = sprintf('%.3f', q_Vitamin_CHigh))  %>% 
  filter(Genus != "g__Chloroplast")

```

# Low vs High
```{r}
ps_vc_rel = transform_sample_counts(ps_vc, function(x) x/ sum(x))
ps_vc_sig = prune_taxa(sig_taxa_asv, ps_vc_rel)
daa_data = psmelt(ps_vc_sig) %>% 
  filter(Vitamin_C == 'Low'| Vitamin_C == 'typical' | Vitamin_C == "High")

daa_data$Genus = factor(daa_data$Genus, levels = vc_daa_sig$Genus)
vc_daa_sig$Genus = factor(vc_daa_sig$Genus, levels = vc_daa_sig$Genus)
daa_data$Vitamin_C = factor(daa_data$Vitamin_C, levels = c('High', 'typical', 'Low'))

daa_boxplot = ggplot(daa_data, aes(y = Genus, x = Abundance*100, fill = Vitamin_C)) +
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(alpha = 0.4)+
  coord_cartesian(xlim = c(0, 4))+
  scale_fill_manual(values = c('High' = '#F5793A', 'Low' = '#E03C8A', 'typical' = '#005AB5'),
                    labels = c('High' = 'High', 'Low' = 'Low', 'typical' = 'Typical'))+
  labs(x = 'Relative Abundance (%)', y = 'Genus')+
  theme_minimal()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = 'black'),
        text = element_text(size = 18),
        axis.text = element_text(size = 18),
        axis.title = element_text(size = 24, face = 'bold'))

daa_lfc = ggplot(vc_daa_sig, aes(y = Genus, x = lfc_Vitamin_CHigh)) +
  geom_bar(stat = 'identity') +
  geom_vline(xintercept = 0, linetype = 'dashed', color = 'black')+
  labs(x = 'Log Fold change', y = NULL)+
  theme_minimal()+
  theme(axis.text.y = element_blank())+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = 'black'),
        text = element_text(size = 18),
        axis.text = element_text(size = 18),
        axis.title = element_text(size = 24, face = 'bold'),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 24, face = 'bold'))

daa_qval = ggplot(vc_daa_sig, aes(y = Genus, x = 1)) +
  geom_text(aes(label = q_label), size = 8) +
  scale_y_discrete(position = 'right')+
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = 'P value (Adjusted)', x = NULL)+
  theme_void()+
  theme(
    panel.grid = element_blank(),
    axis.line = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y.right = element_text(size = 24, face = 'bold', angle = -90, vjust = 0.5),
    plot.margin = margin(l =2, r = 2)
  )

daa_combined = (daa_boxplot | daa_lfc | daa_qval) +
  plot_layout (widths = c(3, 1, 0.7), guides = 'collect') & theme(legend.position = 'right')
ggsave("daa_low_high.png",
       plot = daa_combined, width = 18, height = 10)

```

# Low vs Typical
```{r}

sig_taxa_asv_t = output_genus_vc$res %>% 
  filter(q_Vitamin_Ctypical < 0.05) %>% 
  filter(taxon != "dd228d51656bfa4af8a21464f726fbfc") %>% 
  select(taxon) %>% 
  pull()

tax_df_t = as.data.frame(tax_table(ps_vc)) %>% 
  rownames_to_column(var = 'taxon') %>% 
  filter(taxon %in% sig_taxa_asv_t) 

vc_daa_sig_t = output_genus_vc$res %>% 
  filter(q_Vitamin_Ctypical < 0.05) %>% 
  full_join(tax_df_t, by = 'taxon') %>% 
  select(taxon, lfc_Vitamin_Ctypical, q_Vitamin_Ctypical, Genus) %>% 
  arrange(lfc_Vitamin_Ctypical)%>% 
  mutate(q_label = sprintf('%.3f', q_Vitamin_Ctypical))  %>% 
  filter(Genus != "g__Chloroplast")


ps_vc_sig_t = prune_taxa(sig_taxa_asv_t, ps_vc_rel)
daa_data_t = psmelt(ps_vc_sig_t) %>% 
  filter(Vitamin_C == 'Low'| Vitamin_C == 'typical' | Vitamin_C == "High")

daa_data_t$Genus = factor(daa_data_t$Genus, levels = vc_daa_sig_t$Genus)
vc_daa_sig_t$Genus = factor(vc_daa_sig_t$Genus, levels = vc_daa_sig_t$Genus)
daa_data_t$Vitamin_C = factor(daa_data_t$Vitamin_C, levels = c('High', 'typical', 'Low'))

daa_boxplot_t = ggplot(daa_data_t, aes(y = Genus, x = Abundance*100, fill = Vitamin_C)) +
  geom_boxplot(outlier.shape = NA)+
  geom_jitter(alpha = 0.4)+
  coord_cartesian(xlim = c(0, 4))+
  scale_fill_manual(values = c('High' = '#F5793A', 'Low' = '#E03C8A', 'typical' = '#005AB5'),
                    labels = c('High' = 'High', 'Low' = 'Low', 'typical' = 'Typical'))+
  labs(x = 'Relative Abundance (%)', y = 'Genus')+
  theme_minimal()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = 'black'),
        text = element_text(size = 18),
        axis.text = element_text(size = 18),
        axis.title = element_text(size = 24, face = 'bold'))

daa_lfc_t = ggplot(vc_daa_sig_t, aes(y = Genus, x = lfc_Vitamin_Ctypical)) +
  geom_bar(stat = 'identity') +
  geom_vline(xintercept = 0, linetype = 'dashed', color = 'black')+
  labs(x = 'Log Fold change', y = NULL)+
  theme_minimal()+
  theme(axis.text.y = element_blank())+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = 'black'),
        text = element_text(size = 18),
        axis.text = element_text(size = 18),
        axis.title = element_text(size = 24, face = 'bold'),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 24, face = 'bold'))

daa_qval_t = ggplot(vc_daa_sig_t, aes(y = Genus, x = 1)) +
  geom_text(aes(label = q_label), size = 8) +
  scale_y_discrete(position = 'right')+
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = 'P value (Adjusted)', x = NULL)+
  theme_void()+
  theme(
    panel.grid = element_blank(),
    axis.line = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y.right = element_text(size = 24, face = 'bold', angle = -90, vjust = 0.5),
    plot.margin = margin(l =2, r = 2)
  )

daa_combined_t = (daa_boxplot_t | daa_lfc_t | daa_qval_t) +
  plot_layout (widths = c(3, 1, 0.7), guides = 'collect') & theme(legend.position = 'right')
ggsave("daa_lowtyp.png",
       plot = daa_combined_t, width = 18, height = 10)

daa_combined_t

```


```{r}
prev_table = psmelt(ps_vc_rel) %>% 
  filter(OTU %in% c(sig_taxa_asv, sig_taxa_asv_t)) %>% 
  group_by(Genus) %>%
  summarise(
    n_detected = sum(Abundance > 0),
    total_n = n(),
    prevalence = (n_detected / total_n) * 100
  ) %>% 
  ungroup() %>% 
  arrange(desc(prevalence)) %>% 
  select(Genus, prevalence)

nice_table(prev_table)

tab <- ggtexttable(prev_table, rows = NULL, theme = ttheme("blank")) %>%
 tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 3.5) %>%
  tab_add_hline(at.row = 7, row.side = "bottom", linewidth = 3.5) %>%
  tab_add_title(text = "Supplementary Table 2. Prevalance of Key microbi",
                face = "bold")
tab

```
