---
title: "random_forest_analysis"
output: html_document
date: "2026-02-26"
---

# Part 1: Filtering and Phyloseq Setup

```{r setup}
library(tidyverse)
library(randomForest)
library(caret)
library(ranger)
library(pROC)
library(boot)
library(ggplot2)
library(ggpubr)
library(phyloseq)

#Key info:
# Data set = Parkinsons
# Groups of interest = Vitamin_C "High" and "Low" 
# Filtering included binning Vitamin C levels based on the 33rd and 67th percentile and selecting only PD
# and also selecting only the High and Low ranges of Vitamin C levels, excluding the in between medium range to keep the model at 2 levels

# Load the dataset and aggregate reads to the Genus level
metadata = read.delim('parkinsons_metadata 2.txt', header = TRUE, row.names = 1) 
metadata_PD = subset(metadata, Disease == "PD")
taxonomy = read.delim('taxonomy.tsv', header = TRUE, row.names = "Feature.ID" ) # from qiime2
counts = read.delim('table.txt', skip=1, row.names=1)  # from qiime2
tree = read_tree('tree.nwk')

taxonomy_formatted = taxonomy %>%
  separate(col= Taxon,
           into = c('Domain', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species'),
           sep = '; ', fill = 'right') %>%
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = as.matrix(counts)

PD_sum = metadata_PD|>
  group_by(Sex) |>
  summarise(  
    p33_Vitamin_C = quantile(Vitamin_C, 0.33, na.rm = TRUE),
    p66_Vitamin_C = quantile(Vitamin_C, 0.67, na.rm = TRUE))

PD_grouped = metadata_PD %>% 
  mutate(Vitamin_C =
           case_when(Sex == "Male" & Vitamin_C > 119.2655 ~ "High",
                     Sex == "Male" & Vitamin_C < 82.31294 ~ "Low",
                     Sex == "Male" & Vitamin_C ~ "Typical",
                     Sex == "Female" & Vitamin_C > 165.2305 ~ "High",
                     Sex == "Female" & Vitamin_C < 108.04810 ~ "Low",
                     Sex == "Female" & Vitamin_C ~ "Typical")) %>%
  drop_na(Vitamin_C, Age_onset)

ps <- phyloseq(sample_data(PD_grouped),
               otu_table(counts_formatted, taxa_are_rows = T),
               tax_table(taxonomy_formatted),
               tree)
ps_genus = tax_glom(ps,"Genus")

saveRDS(ps, "phyloseq.rds")
```

# Part 2: Calculating Abundance and Z-transformation

```{r Abundance standardizating}
# Calculate average standardized abundance and identifying top 10~~~~~~~~~~~~
#avg_abundance = taxa_sums(ps_genus)/sum(taxa_sums(ps_genus)) 

#avg_abundance = sort(avg_abundance, decreasing = T)

#top_10 = avg_abundance[1:4]

top_7 = c('4c8288bfbd76958c0c094d87b97650f8','9f79ff73dcbc3e304545d60cdbbca33b',
'84311c29ab5cf09c0720c450dc7c1a43', 'dd228d51656bfa4af8a21464f726fbfc',
'5b73138c8555560a7cd45cb7bd7ca6da','d4dcc0bc5f5a6e517ddf472187dbc2e7')
top_7

# Normalize microbiome data and select only the significant taxa

ps_clr = ps_genus %>% microbiome::transform('clr') 


ps_filt = prune_taxa(top_7,ps_clr)

df = psmelt(ps_filt)

# Add Z transformation to each Genus individually
df_transformed = df %>% 
  group_by(Genus) %>% 
  mutate(Abundance = scale(Abundance)) %>% 
  ungroup() 
df_transformed

df_pivot = df_transformed %>% 
  select(Sample,Age_onset,Genus,Abundance) %>% 
  pivot_wider(names_from = Genus, values_from = Abundance)
df_pivot

df_noNA = df_pivot %>% na.omit()

df_final = df_noNA %>% select(-Sample)
df_final
```
# Part 3: Setting Predictors and Outcome Levels
```{r predictors_and_outcome}
predictors = df_final %>% select(-Age_onset)

outcome = df_final %>% pull(Age_onset)
```

# Part 4: K fold subsetting
```{r k_fold_CV}
k = 10
set.seed(421)
folds = createFolds(outcome, k = k, list = TRUE)
str(folds)
```

# Part 5: Tuning Hyperparameters

```{r hyperparameters}
# mtry parameters were changed to 3,6,10 instead of 5,9,13 to match and fit the 10 variables (genus) used in predicting 
tune_grid = expand.grid(mtry = c(1,3,6), 
                       splitrule = c("variance"),
                       min.node.size = c(10,20,50))
```

# Part 6: Run Random Forest Model

```{r run_rf}
source('randomforest_functions_numeric.R')

pd_model = run_rf(X = predictors, y = outcome, 
                  fold_list = folds,
                  hyper = tune_grid, 
                  rngseed = 421)


rmse_comparison_df = data.frame(
    Fold = seq_along(pd_model$results$rmse_train),
    Train = pd_model$results$rmse_train, ##Train_RMSE = 4.052823
    Test = pd_model$results$rmse_test ##Test_RMSE = 8.283672
  )

  rmse_long = tidyr::pivot_longer(rmse_comparison_df, cols = c(Train, Test), names_to = "Sets", values_to = "RMSE")

  rmse_plot = ggplot(rmse_long, aes(x = Sets, y = RMSE, fill = Sets)) +
    geom_bar(stat = "identity", position = "dodge", aes(width = 0.4)) +
    labs(title = "Mean Fold RMSE ",
         x = "Subset",
         y = "Root Mean Square Error") +
    geom_errorbar(aes(ymin = c(3.97, 7.62), ymax = c(4.08, 8.79)), width = 0.25) +
    theme_classic() +
    theme(legend.position = 'none') +
  scale_fill_discrete(labels = c(
      "Train_RMSE" = "Train",
      "Test_RMSE" = "Test"))
  print(rmse_plot)
  
  
```

# Part 7: Visualize ROC curve

```{r ROC_curve}
# Calculate ROC curve points from RF output
# rmse_test = rmse(pd_model$test_labels$true_labels,
#                pd_model$test_labels$predicted_probabilities)
# rmse_train = rmse(pd_model$train_labels$true_labels,
#                 pd_model$train_labels$predicted_probabilities)
# 
# # True positive rate = sensitivity
# # False positive rate = 1-specificity
# ggplot() +
#   geom_line(aes(x = 1 - rmse_train$specificities, 
#                 y = rmse_train$sensitivities), 
#             color = "red",size=1) +
#   geom_line(aes(x = 1 - rmse_test$specificities,
#                 y = rmse_test$sensitivities), 
#             color = "black",size=1) +
#   geom_abline(slope = 1, intercept = 0, color = "gray", linetype = "dashed",size=1) +
#   labs(x = "False Positive Rate", y = "True Positive Rate") +
#   annotate("text", x = 0.7, y = 0.2, 
#            label = sprintf("Train (red): %.2f (%.2f-%.2f)\nTest (black): %.2f (%.2f-%.2f)",
#            auc(rmse_train), pd_model$auc_train_ci[1], pd_model$auc_train_ci[2],
#            auc(rmse_test), pd_model$auc_test_ci[1], pd_model$auc_test_ci[2]), 
#            size = 6) +
#   theme_minimal(base_size=18)
# R2 = cor(predicted_labels, test_labels$true_labels)^2
#Analysis:
# Can these top 10 taxonomic genera can be used to predict your outcome variable?
# No, these top 10 genus cannot be used reliably to predict high or low Vitamin C inake despite their AUC values at 0.65, due to the wide 95% confidence interval of 0.55-0.72 (0.17 gap) in the test group indicating substantial uncertainty which weakens the precision and stance the resulting AUC value proposes. Additionally, the presence of many jagged  edges in the ROC curve further weakens the credibility and reliability of the predictive model as it indicates the possibility of artifactual effects within the results.
#
# What is a limitations of the analysis?
# K fold is too large = too small sample size per fold to run Random Forest effectively/appropriately.
```

# Part 8 Bonus: Log 2 Fold Change Abundance Comparison 

``` {r Log2fold change}

log_2_fold_abundance <- df |>
  select( Genus, Abundance, Vitamin_C) |>
  group_by(Genus, Vitamin_C ) |>
  summarize(Abundance = abs(mean(Abundance))) |>
  pivot_wider(
    names_from = Vitamin_C,
    values_from = Abundance) |>
  mutate( Log_2_fold_change = log2(High/Low))

log_2_fold_abundance 
```
